GET http://localhost:8081/api/accounts/ewan
//Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJSRkNNIiwiVVNFUl9JRCI6InVzZXIxIiwiVVNFUl9ST0xFIjoiUk9MRV9VU0VSIn0.6Ls3M3E3FLFZt8FfFGAcua6Q2zJxiv8Rbzpaez58ses


